// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASH5EO32hOb-ywbFZEn7hBVTBYMxOjAiY',
    appId: '1:594993480240:web:c74f0805dc7a79ce70e3f5',
    messagingSenderId: '594993480240',
    projectId: 'readingapp8',
    authDomain: 'readingapp8.firebaseapp.com',
    storageBucket: 'readingapp8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB137opAQVtbVz2I9tJqJLp4x3n0TAdYY',
    appId: '1:594993480240:android:5eb21a9bbb83801470e3f5',
    messagingSenderId: '594993480240',
    projectId: 'readingapp8',
    storageBucket: 'readingapp8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bhDmGJbveGDUuQe4xVUcOQ9tnBg4FvI',
    appId: '1:594993480240:ios:8630dd7d545e3bb170e3f5',
    messagingSenderId: '594993480240',
    projectId: 'readingapp8',
    storageBucket: 'readingapp8.appspot.com',
    iosBundleId: 'com.example.readingApp8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bhDmGJbveGDUuQe4xVUcOQ9tnBg4FvI',
    appId: '1:594993480240:ios:8630dd7d545e3bb170e3f5',
    messagingSenderId: '594993480240',
    projectId: 'readingapp8',
    storageBucket: 'readingapp8.appspot.com',
    iosBundleId: 'com.example.readingApp8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASH5EO32hOb-ywbFZEn7hBVTBYMxOjAiY',
    appId: '1:594993480240:web:d9ca98d92ffa6e5470e3f5',
    messagingSenderId: '594993480240',
    projectId: 'readingapp8',
    authDomain: 'readingapp8.firebaseapp.com',
    storageBucket: 'readingapp8.appspot.com',
  );
}
